version: '3.8'
services:

  frontend:
    build:
      context: ../frontend/
      dockerfile: Dockerfile

  db:
    image: postgres:13.0-alpine
    volumes:
      - db:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    build:
      context: ../backend/
      dockerfile: Dockerfile
    restart: always
    volumes:
      - static_value:/app/static/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
    depends_on:
      - backend
      - frontend

volumes:
  db:
  static_value: