# Generated by Django 5.0.3 on 2024-05-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('info', models.CharField(max_length=255, verbose_name='email/номер телефона')),
                ('message', models.TextField(verbose_name='Сообщение')),
            ],
        ),
    ]
