# Generated by Django 5.0.3 on 2024-05-23 11:59

import django.core.validators
import django.db.models.deletion
import project.services
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название фото')),
                ('image', models.ImageField(blank=True, null=True, upload_to=project.services.get_path_upload_image, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg']), project.services.validate_size_image])),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Тип дома')),
            ],
        ),
        migrations.CreateModel(
            name='ReleasedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainPhoto', models.ImageField(blank=True, null=True, upload_to=project.services.get_path_upload_image, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg']), project.services.validate_size_image])),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название дизайн-проекта')),
                ('location', models.CharField(max_length=255, verbose_name='Город')),
                ('complexName', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название жилого комплекса')),
                ('square', models.IntegerField(blank=True, null=True, verbose_name='Площадь объекта')),
                ('description', models.TextField(verbose_name='Описание')),
                ('photos', models.ManyToManyField(to='project.photo')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.type')),
            ],
        ),
        migrations.CreateModel(
            name='DesignProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название дизайн-проекта')),
                ('location', models.CharField(max_length=255, verbose_name='Город')),
                ('complexName', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название жилого комплекса')),
                ('square', models.IntegerField(blank=True, null=True, verbose_name='Площадь объекта')),
                ('photos', models.ManyToManyField(to='project.photo')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.type')),
            ],
        ),
    ]
